base/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booksapp.urls'))
]

booksapp/urls.py
from django.urls import path

from booksapp.views import BookListView, BookCreateView, BookUpdateView, BookDeleteView, book_import

urlpatterns = [
    path('', BookListView.as_view(), name='book_list'),
    path('book/add', BookCreateView.as_view(), name='book_create'),
    path('book/<int:pk>/update/', BookUpdateView.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', BookDeleteView.as_view(), name='book_delete'),
    path('book/import/', book_import, name='book_import'),
]

booksapp/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Author(models.Model):
    author_name = models.CharField(max_length=255)

    def __str__(self):
        return self.author_name


class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ManyToManyField(Author)
    publication_date = models.PositiveIntegerField(verbose_name="Publication date",
                                                   validators=[
                                                       MaxValueValidator(9999),
                                                       MinValueValidator(1)
                                                   ])
    isbn = models.CharField(max_length=13)
    number_of_pages = models.IntegerField()
    cover_link = models.URLField()
    publication_language = models.CharField(max_length=255)

booksapp/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

booksapp/views.py
import datetime

import requests
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from booksapp.forms import BookForm
from booksapp.models import Book, Author


class BookListView(ListView):
    model = Book
    template_name = 'list_books.html'

    def get_queryset(self):
        # Get the search parameters from the request.
        search_title = self.request.GET.get('search_title', '')
        search_author = self.request.GET.get('search_author', '')
        search_language = self.request.GET.get('search_language', '')
        search_publication_date_from = self.request.GET.get('search_publication_date_from', '')
        search_publication_date_to = self.request.GET.get('search_publication_date_to', '')

        # Filter the books based on the search parameters.
        books = Book.objects.all()
        if search_title:
            books = books.filter(title__contains=search_title)
        if search_author:
            author = Author.objects.filter(author_name__contains=search_author)
            if not author:
                # Need to implement!
                return books
            books = books.filter(author=author[0])
        if search_language:
            books = books.filter(publication_language__contains=search_language)
        if search_publication_date_from and search_publication_date_to:
            books = books.filter(publication_date__range=(search_publication_date_from, search_publication_date_to))
        elif search_publication_date_from:
            books = books.filter(publication_date__gte=search_publication_date_from)
        elif search_publication_date_to:
            books = books.filter(publication_date__lte=search_publication_date_to)

        return books


class BookCreateView(CreateView):
    form_class = BookForm
    # model = Book
    # fields = '__all__'
    template_name = 'create_book.html'

    def get_success_url(self):
        return reverse_lazy('book_list')


class BookUpdateView(UpdateView):
    form_class = BookForm
    # model = Book
    # fields = '__all__'
    template_name = 'update_book.html'

    def get_success_url(self):
        return reverse_lazy('book_list')


class BookDeleteView(DeleteView):
    model = Book
    success_url = reverse_lazy('book_list')
    template_name = 'delete_book.html'

    def get_success_url(self):
        return reverse_lazy('book_list')


def book_import(request):
    if request.method == 'POST':
        # Get the book title from the request.
        book_title = request.POST['book_title']

        # Make a request to the Google Books API.
        response = requests.get(
            'https://www.googleapis.com/books/v1/volumes',
            params={'q': book_title}
        )

        # Check if the request was successful.
        if response.status_code == 200:
            # Get the book data from the response.
            book_data = response.json()['items'][0]['volumeInfo']

            # Create a list of authors from the book data.
            authors = []
            for author_name in book_data['authors']:
                author, created = Author.objects.get_or_create(author_name=author_name)
                authors.append(author)

            try:
                book_data['publishedDate'] = datetime.datetime.strptime(book_data['publishedDate'], "%Y-%m-%d").strftime("%Y")
            except ValueError:
                pass

            # Create a new book object in the database.
            book = Book(
                title=book_data['title'],
                publication_date=book_data['publishedDate'],
                isbn=book_data['industryIdentifiers'][0]['identifier'],
                number_of_pages=book_data['pageCount'],
                cover_link=book_data['imageLinks']['thumbnail'],
                publication_language=book_data['language'],
            )
            book.save()
            book.author.set(authors)

            # Return a redirect to the book list page.
            return HttpResponseRedirect(reverse_lazy('book_list'))
        else:
            # Display an error message to the user.
            return render(request, 'import_book.html', {'error_message': 'Could not import book.'})

    return render(request, 'import_book.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Bookstore{% endblock %}</title>
    <!-- Include Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Bookstore</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'book_list' %}">Books</a>
                </li>
                <li class="nav-item">
{#                    <a class="nav-link" href="{% url 'author_list' %}">Authors</a>#}
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Include Bootstrap JS and dependencies -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/create_book.html
{% extends 'base.html' %}

{% block content %}
    <h1>Create New Book</h1>

    {% if form.errors %}
        <ul class="errorlist">
            {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ field.name }} - {{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    {% endif %}

    <form action="{% url 'book_create' %}" method="post">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_title">Title</label>
            <input type="text" name="title" id="id_title" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="{{ form.sender.id_for_label }}">Author</label>
            <select multiple name="{{ form.author.name }}" id="{{ form.sender.id_for_label }}" class="form-control" required>
                {% for instance in form.author.field.queryset %}
                    <option value="{{ instance.pk }}">{{ instance.author_name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="publication_date">Publication Date</label>
            <input type="number" name="publication_date" id="publication_date" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="isbn">ISBN</label>
            <input type="text" name="isbn" id="isbn" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="number_of_pages">Number of pages</label>
            <input type="number" name="number_of_pages" id="number_of_pages" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="cover_link">Cover link</label>
            <input type="url" name="cover_link" id="cover_link" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="publication_language">Publication language</label>
            <input type="text" name="publication_language" id="publication_language" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-success mt-2">Create Book</button>
    </form>
{% endblock %}

templates/delete_book.html
{% extends 'base.html' %}

{% block content %}
    <h1>Are you sure you want to delete {{ object.title }} with id {{ object.pk }}?</h1>

    <form action="{% url 'book_delete' pk=object.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger mt-2">Delete Book</button>
    </form>
{% endblock %}

templates/import_book.html
{% extends 'base.html' %}

{% block content %}
    <h1>Import Book</h1>

    <form action="{% url 'book_import' %}" method="post">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_book_title">Title</label>
            <input type="text" name="book_title" id="id_book_title" class="form-control" required>
        </div>

        <button type="submit" class="btn btn-primary mt-2">Import Book</button>
    </form>

    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}
{% endblock %}

templates/list_books.html
{% extends 'base.html' %}

{% block content %}
    <h1>Book List</h1>

    {% if form.errors %}
        <ul class="errorlist">
            {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ field.name }} - {{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    {% endif %}

    <form action="{% url 'book_list' %}" method="get">
        {% csrf_token %}
        Search by:
        <div class="input-group mb-3">
            <input type="text" class="form-control" name="search_title" placeholder="Title">
            <input type="text" class="form-control" name="search_author" placeholder="Author">
            <input type="text" class="form-control" name="search_language" placeholder="Language">
            <input type="number" class="form-control" name="search_publication_date_from" placeholder="Publication date from">
            <input type="number" class="form-control" name="search_publication_date_to" placeholder="Publication date to">
            <button type="submit" class="btn btn-primary">Search</button>
        </div>

    </form>

    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Authors</th>
                <th>Publication Date</th>
                <th>ISBN</th>
                <th>Number of pages</th>
                <th>publication_language</th>
            </tr>
        </thead>
        <tbody>
            {% for book in book_list %}
                <tr>
                    <td>{{ book.title }}</td>
                    <td>
                        <ul style="list-style-type: none;">
                            {% for author in book.author.all %}
                                <li> - {{ author.author_name }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>{{ book.publication_date }}</td>
                    <td>{{ book.isbn }}</td>
                    <td>{{ book.number_of_pages }}</td>
                    <td>{{ book.publication_language }}</td>
                    <td>
                        <a href="{% url 'book_update' pk=book.pk %}" class="btn btn-primary">Edit</a>
                        <a href="{% url 'book_delete' pk=book.pk %}" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'book_create' %}" class="btn btn-success">Add New Book</a>
    <a href="{% url 'book_import' %}" class="btn btn-outline-success">Import book</a>
{% endblock %}

templates/update_book.html
{% extends 'base.html' %}

{% block content %}
    <h1>Update Book</h1>

    {% if form.errors %}
        <ul class="errorlist">
            {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ field.name }} - {{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    {% endif %}

    <form action="{% url 'book_update' pk=book.pk %}" method="post">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_title">Title</label>
            <input type="text" name="title" id="id_title" value="{{ form.title.value }}" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="{{ form.author.id_for_label }}">Author</label>
            <select multiple name="{{ form.author.name }}" id="{{ form.author.id_for_label }}" class="form-control" required>
                {% for instance in form.author.field.queryset %}
                    <option value="{{ instance.pk }}" {% if instance.pk == form.author.value %} selected{% endif %}>{{ instance.author_name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="publication_date">Publication Date</label>
            <input type="number" name="publication_date" value="{{ form.publication_date.value|date:'Y-m-d' }}" id="publication_date" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="isbn">ISBN</label>
            <input type="text" name="isbn" id="isbn" class="form-control" value="{{ form.isbn.value }}" required>
        </div>

        <div class="form-group">
            <label for="number_of_pages">Number of pages</label>
            <input type="number" name="number_of_pages" id="number_of_pages" class="form-control" value="{{ form.number_of_pages.value }}" required>
        </div>

        <div class="form-group">
            <label for="cover_link">Cover link</label>
            <input type="url" name="cover_link" id="cover_link" class="form-control" value="{{ form.cover_link.value }}" required>
        </div>

        <div class="form-group">
            <label for="publication_language">Publication language</label>
            <input type="text" name="publication_language" id="publication_language" class="form-control" value="{{ form.publication_language.value }}" required>
        </div>
        <button type="submit" class="btn btn-success mt-2">Update Book</button>
    </form>
{% endblock %}